# Generated by Django 2.2.6 on 2022-10-26 09:43

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProcessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('graphql_query', models.TextField()),
                ('relay_data_locator', django.contrib.postgres.fields.jsonb.JSONField()),
                ('default_response', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('relay_json_schema', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'data_processors',
            },
        ),
        migrations.CreateModel(
            name='RelayEventLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('source_event_name', models.CharField(max_length=100)),
                ('destination_relay_name', models.CharField(max_length=512, null=True)),
                ('relay_type', models.CharField(max_length=20, null=True)),
                ('relay_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('status', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'relay_logs',
            },
        ),
        migrations.CreateModel(
            name='RelayProcessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('source_event_id', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('relay_type', models.CharField(max_length=20)),
                ('relay_system', models.CharField(max_length=128)),
                ('relay_event_rules', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('context_data_locator', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('relay_http_endpoint_rules', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('data_processor_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'relay_processors',
            },
        ),
        migrations.CreateModel(
            name='SourceEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('source_event', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('input_json_schema', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'source_events',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSourceEvent',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('source_event', models.CharField(max_length=128)),
                ('input_json_schema', django.contrib.postgres.fields.jsonb.JSONField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical source event',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRelayProcessor',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('source_event_id', models.IntegerField(default=0)),
                ('relay_type', models.CharField(max_length=20)),
                ('relay_system', models.CharField(max_length=128)),
                ('relay_event_rules', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('context_data_locator', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('relay_http_endpoint_rules', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('data_processor_id', models.IntegerField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical relay processor',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDataProcessor',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('graphql_query', models.TextField()),
                ('relay_data_locator', django.contrib.postgres.fields.jsonb.JSONField()),
                ('default_response', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('relay_json_schema', django.contrib.postgres.fields.jsonb.JSONField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical data processor',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
